@REM ************************************************************************************
@REM Description: setenv para projeto Distributed Drive (projeto_finalSD2025)
@REM Author: sebas
@REM ************************************************************************************

@SET SCRIPT_ROLE=%1

@REM ==== INFO DO TEU PC E IDE ====
@SET USERNAME=sebas
@SET WORKDRIVE=C
@SET JDK=C:\Users\sebas\.jdks\corretto-1.8.0_422
@SET CURRENT_IDE=IntelliJ

@REM ==== DADOS DO PROJETO ====
@SET JAVAPROJ_NAME=projeto_finalSD2025
@SET JAVAPROJ=C:\Users\sebas\Desktop\faculdade\sd\projeto_finalSD2025

@REM ==== PACKAGE ====
@SET PACKAGE=distributed_drive
@SET PACKAGE_PREFIX=edu.ufp.inf.sd.rmi
@SET PACKAGE_PREFIX_FOLDERS=edu/ufp/inf/sd/rmi
@SET SERVICE_NAME_ON_REGISTRY=DDService
@SET CLIENT_CLASS_PREFIX=DD
@SET SERVER_CLASS_PREFIX=DD
@SET CLIENT_CLASS_POSTFIX=Client
@SET SERVER_CLASS_POSTFIX=Server
@SET SERVANT_IMPL_CLASS_POSTFIX=Impl

@REM ==== REDE ====
@SET MYLOCALIP=localhost
@SET REGISTRY_HOST=%MYLOCALIP%
@SET REGISTRY_PORT=1099
@SET SERVER_RMI_HOST=%REGISTRY_HOST%
@SET SERVER_RMI_PORT=1098
@SET SERVER_CODEBASE_HOST=%SERVER_RMI_HOST%
@SET SERVER_CODEBASE_PORT=8000
@SET CLIENT_RMI_HOST=%REGISTRY_HOST%
@SET CLIENT_RMI_PORT=1097
@SET CLIENT_CODEBASE_HOST=%CLIENT_RMI_HOST%
@SET CLIENT_CODEBASE_PORT=8000

@REM ==== PATHS E NOMES DE CLASSES ====
@SET JAVAPACKAGE=%PACKAGE_PREFIX%.%PACKAGE%
@SET JAVAPACKAGEROLE=%PACKAGE_PREFIX%.%PACKAGE%.%SCRIPT_ROLE%
@SET JAVAPACKAGEPATH=%PACKAGE_PREFIX_FOLDERS%/%PACKAGE%/%SCRIPT_ROLE%
@SET JAVASCRIPTSPATH=%PACKAGE_PREFIX_FOLDERS%/%PACKAGE%/runscripts
@SET JAVASECURITYPATH=edu\\ufp\\inf\\sd\\rmi\\%PACKAGE%\\securitypolicies
@SET SERVICE_NAME=%SERVICE_NAME_ON_REGISTRY%
@SET SERVICE_URL=rmi://%REGISTRY_HOST%:%REGISTRY_PORT%/%SERVICE_NAME%

@SET PATH=%PATH%;.;%JDK%\bin

@IF "%CURRENT_IDE%"=="IntelliJ" (
    @SET JAVAPROJ_CLASSES=out\\production\\%JAVAPROJ_NAME%\\
    @SET JAVAPROJ_SRC=src
    @SET JAVAPROJ_DIST=out\\artifacts\\%JAVAPROJ_NAME%\\
    @SET JAVAPROJ_DIST_LIB=lib
)

@SET JAVAPROG_CLASSES_FOLDER=%JAVAPROJ%\%JAVAPROJ_CLASSES%
@SET JAVAPROJ_DIST_FOLDER=%JAVAPROJ%\%JAVAPROJ_DIST%
@SET JAVAPROJ_JAR_FILE=%JAVAPROJ_NAME%.jar
@SET CLASSPATH=.;%JAVAPROG_CLASSES_FOLDER%

@SET ABSPATH2CLASSES=%JAVAPROJ%\%JAVAPROJ_CLASSES%
@SET ABSPATH2SRC=%JAVAPROJ%\%JAVAPROJ_SRC%
@SET ABSPATH2DIST=%JAVAPROJ%/%JAVAPROJ_DIST%

@SET SERVER_CODEBASE=http://%SERVER_CODEBASE_HOST%:%SERVER_CODEBASE_PORT%/%JAVAPROJ_JAR_FILE%
@SET CLIENT_CODEBASE=http://%CLIENT_CODEBASE_HOST%:%CLIENT_CODEBASE_PORT%/%JAVAPROJ_JAR_FILE%

@SET SERVER_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\serverAllPermition.policy
@SET CLIENT_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\clientAllPermition.policy
@SET SETUP_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\setup.policy
@SET RMID_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\rmid.policy
@SET GROUP_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\group.policy
